### ISSUE TITLE
pabbrev-debug-message invalid-function

### ISSUE THREAD

**Issue by FurongPeng** [phillord/pabbrev#1]
My emacs: 24.4
OS: osx

init.el configuration:

(require 'pabbrev)
(global-pabbrev-mode)
(provide 'init-pabbrev)

When I idle in emas, I get the following error message.

Error running timer `pabbrev-idle-timer-function': (invalid-function pabbrev-debug-message)

**Comment by phillord** [comment]
I've pushed a new version to ELPA, Marmalade and MELPA which should fix. Let me know if not!

Thanks for the report!

**Comment by FurongPeng** [comment]
Yes, the updated version works well.

Thank you.

**Comment by phillord** [comment]
Good stuff!
